config/routes.rb
Launcherr::Application.routes.draw do
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts  do  #->Prelang (voting/acts_as_votable)
  collection do
    get "my_project"
    get "inbox"
  end
  member do
    get "vote"
  end
end
 

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'posts#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                      :integer          not null, primary key
#  project_name            :string(255)
#  quick_pitch             :text
#  full_pitch              :text
#  user_id                 :integer
#  youtube_id              :string(255)
#  to_the_table            :text
#  compensation_method     :text
#  location                :string(255)
#  tags                    :text
#  created_at              :datetime
#  updated_at              :datetime
#  coverimage_file_name    :string(255)
#  coverimage_content_type :string(255)
#  coverimage_file_size    :integer
#  coverimage_updated_at   :datetime
#  logoimage_file_name     :string(255)
#  logoimage_content_type  :string(255)
#  logoimage_file_size     :integer
#  logoimage_updated_at    :datetime
#  url                     :string(255)
#  skills                  :string(255)
#

class Post < ActiveRecord::Base
  belongs_to :user
 
  attr_accessible :project_name, :quick_pitch, :coverimage, :logoimage, :full_pitch, :skills, :youtube_id, :to_the_table, :compensation_method, :location, :url, :content, :name, :tag_list
 
 has_attached_file :coverimage 
 has_attached_file :logoimage 

 validates_attachment :coverimage, content_type: { content_type: /\Aimage\/.*\Z/ }
 validates_attachment :logoimage, content_type: { content_type: /\Aimage\/.*\Z/ } 
 #validates_formatting_of :youtube_id, using: :url
  # acts_as_votable 
  #attr_accessible :content, :name, :tag_list
acts_as_taggable


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def my_project
   @user = User.find(current_user.id)
    @posts = @user.posts
  end

  def inbox
    @messages = current_user.received_messages
  
  end



  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    @post.user = current_user
    
       respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @post.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:project_name, :quick_pitch, :coverimage, :logoimage, :full_pitch, :skills , :user_id, :youtube_id, :to_the_table, :compensation_method, :location,:url, :body, :topic,:content, :name, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/confirmation_instructions.html.erb
<p>Welcome <%= @name %>!</p>

<p> Thanks for signing up to Launcherr, we are excited to see what you can achieve here </p>

<p>To confirm your account click the link below:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>

<p> Regards, <br>
	The team @ Launcherr </p>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Post %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/inbox.html.erb
<br><br><h2> Messages Are </h2>
<% if @messages.nil? %>
<h4>----No Messages --></h4>
<%else%>
<% @messages.each do |m| %>
    <%= m.body %>
    <%= m.topic %><br>
<% end %>
<% end %>

app/views/posts/index.html.erb
 
<!--CSS-->

 <!-- PASSIONATE -->
      <div id="passionate" class="horizontalsection text-light parallax-section">
      <div class="horizontalinner wrapper align-center">
        <h2> build cool things with cool people </h2>
        <div class="spacer spacer-small"></div>
        <p>
          <% if user_signed_in? %>
          <a href="./posts/new" class="scroll-to sr-button sr-button4 medium-button">Launch Idea</a>
          <% else %>
          <a href="./login" class="scroll-to sr-button sr-button4 medium-button">Launch Idea</a>
          <% end %>
        </p>
      </div>
    </div>
<br> <br>

<script>
<div class="container" style="padding-right:50px;padding-left:50px;">
<link rel="stylesheet" href="assets/gridGallery.css" /> </script>
<div id="grid">
         <% @posts.each do |post| %>
        <div class="box" data-url="posts/<%=post.id%>" data-category="Illustrations">
 
            <%=image_tag post.logoimage %> 
           
            <div data-image="./assets/bar.png" ></div>
            
            <div class="thumbnail-caption">
                 <h3g> <%= post.project_name %></h3g>
            <br>
            <h5g><i class="fa fa-map-marker">  </i> <%= post.location %></h5g>
              <br>
             
<h6g> <%= post.quick_pitch %> </h6g>
            </div>

        </div>
        <%end%>
<br>

</div>

<!-- SCRIPTS FOR THE PLUGIN -->

<script src="assets/jquery-1.9.1.min.js"></script>
<script src="assets/rotate-patch.js"></script>
<script src="assets/gridGallery.min.js"></script>
<script>
  
    $(function(){
        //INITIALIZE THE PLUGIN
        $('#grid').grid({

          showFilterBar: true, //Show the navigation filter bar at the top
            imagesToLoad: 4, //The number of images to load when you click the load more button
            imagesToLoadStart: 15, //The number of images to load when it first loads the grid
            lazyLoad: false, //If you wish to load more images when it reach the bottom of the page
            isFitWidth: true, //Nedded to be true if you wish to center the gallery to its container
            horizontalSpaceBetweenThumbnails: 15, //The space between images horizontally
            verticalSpaceBetweenThumbnails: 15, //The space between images vertically
            columnWidth: 'auto', //The width of each columns, if you set it to 'auto' it will use the columns instead
            columns: 5, //The number of columns when you set columnWidth to 'auto'
            columnMinWidth: 220, //The minimum width of each columns when you set columnWidth to 'auto'
            isAnimated: true, //If you wish the gallery to have animated effects when resizing the grid
            caption: true, //Show the caption in mouse over
            captionType: 'grid', // 'grid', 'grid-fade', 'classic' the type of caption effect
            lightBox: true, //Do you want the lightbox?
            lightboxKeyboardNav: true, //Keyboard navigation of the next and prev image
            lightBoxSpeedFx: 500, //The speed of the lightbox effects
            lightBoxZoomAnim: true, //Do you want the zoom effect of the images in the lightbox?
            lightBoxText: true, //If you wish to show the text in the lightbox
            lightboxPlayBtn: true, //Show the play button?
            lightBoxAutoPlay: false, //The first time you open the lightbox it start playing the images
            lightBoxPlayInterval: 4000, //The interval in the auto play mode
            lightBoxShowTimer: true, //If you wish to show the timer in auto play mode
            lightBoxStopPlayOnClose: false, //Do you want pause the auto play mode when you close the lightbox?

        });
    });
       
</script>

    

app/views/posts/my_project.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => Post %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:project_name) %></th>
      <th><%= model_class.human_attribute_name(:quick_pitch) %></th>
      <th><%= model_class.human_attribute_name(:full_pitch) %></th>
      <th><%= model_class.human_attribute_name(:youtube_id) %></th>
      <th><%= model_class.human_attribute_name(:to_the_table) %></th>
      <th><%= model_class.human_attribute_name(:compensation_method) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.project_name %></td>
        <td><%= post.quick_pitch %></td>
        <td><%= post.full_pitch %></td>
        <td><%= post.youtube_id %></td>
        <td><%= post.to_the_table %></td>
        <td><%= post.compensation_method %></td>
        <td><%= post.location %></td>
        <td><%= post.tags %></td>
        <td><%=l post.created_at, format: :long %></td>
        <td>
          <%= link_to post_path(post), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to  post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
 <!-- PASSIONATE -->
			<div id="passionate" class="horizontalsection text-light parallax-section2">
			<div class="horizontalinner wrapper align-center">
			  <p><h2> Ready To Launch	</h2></p>
				<div class="spacer spacer-small"></div>
				
			</div>
		</div>

<%- model_class = Post -%>
<div id="portfolio-singlee" class="section-innere">
          <div class="wrapper clearfix"><br>
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New Project'], :model => Post %></h3>
</div></div>
<%= render :partial => 'form' %><br>

app/views/posts/reset_password_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

app/views/posts/show.html.erb
     <title><%= @post.project_name %>| Launcherr </title>
      

      <!-- PAGEBODY -->
      <div class="page-body"></div>

        <!-- Cover Photo -->
        <div class="top-area">
          <%=image_tag @post.coverimage.url %></div>
        </div>
          <ul class="socialmedia-widget social-share">
            <li class="facebook">
              <a href="">Facebook</a>
            </li>
            <li class="twitter">
              <a href="">Tweet</a>
            </li>
            <li class="googleplus">
              <a href="">Google Plus</a>
            </li>
            <li class="pinterest">
              <a href="">Pinterest</a>
            </li>
          </ul><br>
        </div>


        <!-- MAIN PITCH SECTION -->
        <section id="portfolio">
          <div id="portfolio-singlee" class="section-innere">
            <div class="wrapper clearfix">

              <div class="main-content left-float">
                <!-- VIDEO SECTION -->
                <div class="entry-media portfolio-media">
                  <iframe width="400" height="230" src= "<%= @post.youtube_id %>.url"
                                     frameborder="1" scrolling="no"> </iframe>
                                     
                </div>
                <!-- MAIN DESCRIPTION -->
                <br> <h5><strong>About <%= @post.project_name %> </h6></strong>
<br><%= @post.full_pitch %>
<br>

              <!-- COMPENSATION --></p>
              <h6><strong> How  You Will Be Compensated</strong></h6>
              <p><%= @post.compensation_method %></p>

                <!-- What Can Project Author Bring to the Table?-->                
                </p>
              <h6><strong> What can I bring to the table? </strong></h6>

              <h6><strong><%= @post.url %></strong>
              <p><%= @post.to_the_table %>
                <br> <br> 
                 </div>

                <!-- END .main-content -->

                <!-- PROJECT INFO // SIDEBAR -->
              </p>
              <aside class="right-float">
                            
                <!-- Start Location -->
                <div class="entry-content portfolio-content">


                  <!-- Skill -->
                   <div class="entry-content portfolio-content"> <h4><strong> Skills </strong></h4></div>
                    <ul>
                    <%#=raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')  %>
                    <% @post.tag_list.each do |t|  %>
                    <li><%= t %></li>
                    <% end %>


                  </ul>
                  <!-- TEAM NEEDED -->
               <h4><strong><%= @post.project_name %></strong></h4></div><br>
                                  <div class="entry-content portfolio-content"> <h4><strong> Team Needed</strong></h4></div>

                  <ul>
                    • Architect
                  </ul>
                  <ul>
                    • Timber Specialist
                  </ul>
                  <ul>
                    • 
                  Plumber
                  </ul>
                  <ul>
                    • Electrician
              </ul>
                  <ul>
                    <p>
                    • Handyman                  </p><br>
                  </ul>
                                  <br>
                                  <a data-toggle="modal" href="#myModal" class="sr-button sr-button5 big-button">JØIN TEAM</a></p>
                
                 
                  <h6> <i class="fa fa-map-marker"> </i> <%= @post.location %></h6>
                  <h6> <i class="fa fa-link"> </i> <%= @post.url %></h6>
                  <h6> <i class="fa fa-clock-o"> </i> <%= @post.created_at %></i>.</h6><br><br>
                  <p><!-- END LOCATION -->
                                  
                        </p><br><br><br>
                                  
                                  
                                
                    <!-- END COUNTDOWN -->
                    
              
                        

                  <!-- START TAGS  -->
                                     <div class="widget tag-widget">
                      
                       
                   
                </div> <br><br>

                
                                
                    <!-- End tag-widget -->
                                     
                                
                               
                                
                            <!-- SIDEBAR -->

      </div>
            <!-- END .wrapper -->

            <div class="spacer spacer-big"></div>

          </div>
          <div class="modal hide" id="myModal"><!-- note the use of "hide" class -->
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>Join <%= @post.project_name %></h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="sr-button sr-button2 mini-button" data-dismiss="modal">Bail</a><!-- note the use of "data-dismiss" -->
    <a href="#" class="sr-button sr-button5 mini-button">Join Team</a>
  </div>
</div>​
          <!-- END #portfolio-single .section-inner --><!-- END SECTION #portfolio-->
        <!-- PORTFOLIO SECTION -->

        <!-- FOOTER -->

app/views/posts/unlock_instructions.html.erb
<p>Hello <%= @resource.email %>!</p>

<p>Your account has been locked due to an excessive number of unsuccessful sign in attempts.</p>

<p>Click the link below to unlock your account:</p>

<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>

<p> Regards, <br>
	The team @ Launcherr </p>