config/routes.rb
Launcherr::Application.routes.draw do
  get 'tags/:tag', to: 'posts#index', as: :tag
  resources :posts  do  #->Prelang (voting/acts_as_votable)
  collection do
    get "my_project"
    get "inbox"
  end
  member do
    get "vote"
  end
end
 

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'posts#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/views/layouts/_myprojects.html.erb
<!--My projects--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-US">
	<!--<![endif]-->

<head>
  <meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Launcherr | Crowdsourcing Creative Projects</title>
		<!-- FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,800,600|Raleway:300,600,900' rel='stylesheet' type='text/css'>
		<!-- FONTS -->
		 <!-- Bootstrap CSS-->
    <link href="/files/css/bootstrap.min.css" rel="stylesheet" media="screen">
		<!-- CSS -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- FAVICON -->
		<link rel="shortcut icon" href="files/uploads/favicon.png"/>
		<!-- FAVICON -->

		
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? %><meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<!-- header -->
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>
<div id="page-content" class="fixed-header">
<header id="header">
				<div class="header-inner wrapper clearfix">

					<div id="logo" class="left-float">
						<a id="defaut-logo" class="logotype" href="/">
						<%= image_tag("headerlogo.png", :size => "64x64", :alt => "Show Group") %></a>
					</div>

					<div class="menu left-float clearfix">
						<nav id="main-nav">
							</li>

							</ul>
						</nav>
						<nav id="menu-controls">
							
							
						</nav>
					</div>
					<center>
					<div class="right-float" style="text-align: left">
					<!-- Logged in Header-->	
<% if defined?(Devise) %>
        <% if user_signed_in? %>
	<nav id="main-nav">
<ul>

<li>
<a href="#"> Welcome </a>
<ul class="sub-menu">
           <li><%= link_to "My Projects", my_project_posts_path %></li>
</li>

<li><%= link_to "My Account", edit_user_registration_path %></li>
</li>
<% x = 7 %>
<li><%= link_to "Inbox", inbox_posts_path %></li>
</li>
<li><%= current_user.received_messages.count %></li>
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
</li>

</ul>
</li>

</ul>
							<!-- END Logged in Header -->
<% else %>
				<div class="right-float" style="text-align: left">
						<nav id="main-nav">
							<ul>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
						</nav>
					</div>
					</center>

				</div>
				</header>
		</div>
			
                      
	<% if flash[:error] %>
  <p class="error" > <%= flash[:error].html_safe %></p><br />
<%end%>
<% if flash[:alert] %>
  <p class="error" > <%= flash[:alert].html_safe %></p><br />
<%end%>

		


<%= yield %>



<!-- FOOTER -->
				<footer>
				  <div class="footerinner wrapper align-center text-light">
						<a id="backtotop" href="#" class="sr-button sr-buttonicon small-iconbutton"><i class="fa fa-angle-up"></i></a>
						<p class="footer-logo"><%= image_tag("footerlogo.png", :size => "64x64", :alt => "Show Group") %></a>
						</p>
					<ul class="socialmedia-widget social-share">
							<li class="facebook">
								<a href="http://facebook.com/lnchrr" target="_blank">Facebook</a>
							</li>
							<li class="twitter">
								<a href="http://twitter.com/lnchrr" target="_blank">Tweet</a>
							</li>
							<li class="linkedin">
								<a href="http://www.linkedin.com/company/launcherr" target="_blank"> Linkedin</a>
							</li>
							<li class="instagram">
								<a href="http://instagram.com/lnchrr" target="_blank">Instagram</a>
							</li>
				    </ul>
					  
					  <p class="copyright"><a href="http://blog.launcherr.com/about">About</a> | <a href="http://blog.launcherr.com">Blog</a> | <a href="http://blog.launcherr.com/contact">Contact</a></p>
					  </p>
						<p class="copyright">Copyright &copy; 2014 - Launcherr - Crowdsourcing Creative Projects
				    </p>
					</div>
		  </footer>
				<!-- FOOTER -->
			<script>

				$( 'document' ).ready( function( ) {
					//INITIALIZE THE PLUGIN
					$( '#grid' ).grid( );

				} );

			</script>
                

</body>
</html>

app/views/layouts/project.html.erb
<title> <th><%= model_class.human_attribute_name(:project_name) %></th> | Launcherr Crowdsourcing Skills To Launch Ideas</title>
			<!-- Project -->
			<%- model_class = Post -%>
	  <div class="page-body">

				<style>
					.image {
						position: relative;
						width: 100%; /* for IE 6 */
					}

					h2 {
						position: absolute;
						top: 200px;
						left: 0;
						width: 100%;
						margin-top: 30px !important;
					}
				</style>
				<!-- Cover Photo -->
				<div class="top-area" >
				  <th><%= model_class.human_attribute_name(:coverimage) %></th>
				</div>
                
                <!-- LOGO/SQUARE PHOTO -->
                
		<img src="coverlogo.png"  alt="" style="top: -110px;width:200px; position: relative; margin-right: 265px; -webkit-border-radius:5px;-moz-border-radius:5px;-ms-border-radius:5px;-o-border-radius:5px;border-radius:5px; border: 5px solid #FFFFFF;"   align="right" />
                
                <!-- LOGO END -->

				<div class="section-title project-title hhh" >
				  <h2 class="<th><%= model_class.human_attribute_name(:project_name) %></th>"</h2>
					<br>
				</div>
				<!-- end cover photo-->

				<!-- MAIN CONTENT -->
				<section id="portfolio">
					<div id="portfolio-singlee" class="section-innere">
						<div class="wrapper clearfix">

						  <div class="main-content left-float">
								
                                
                                <!-- VIDEO PITCH --><br><br>
                                
							  <div class="entry-media portfolio-media">
									<iframe width="400" height="230" src="<th><%= model_class.human_attribute_name(:youtube_id) %></th>
									" frameborder="0" scrolling="no"></iframe>

							  </div>
								<!-- FULL PITCH -->
								<th><%= model_class.human_attribute_name(:full_pitch) %></th>
						      
						      <!-- COMPENSATION --></p>
							<h6><strong> How  You Will Be Compensated?<br>
								  <br>
								</strong></h6>
							 <p> <th><%= model_class.human_attribute_name(:compensation_method) %></th> </p>
							    
							    <!-- END COMPENSATION --><br><br> 

							  <!-- insert "what can i bring to the table section" -->								
						    </p>
							<h6><strong> What can I bring to the table? </strong></h6>
						   <p> <th><%= model_class.human_attribute_name(:to_the_table) %></th></p>
<br>
							    
						      <!-- Main Content Join Team Button-->

						      <br>
						      <a href="#" class="sr-button sr-button5 big-button">JØIN TEAM</a>
						      </a>
						      <br><br>
						    </p>

							</div>
							<p>

								<!-- END MAIN CONTENT -->

								<!-- PROJECT INFO // SIDEBAR -->
							</p>
							<aside class="right-float">

<!-- Start Location -->
								<div class="entry-content portfolio-content"> <h4><strong>  <th> <%= model_class.human_attribute_name(:project_name) %></th></strong></h4></div>
									<h6> <i class="fa fa-map-marker"> </i> <th><%= model_class.human_attribute_name(:location) %></th></h6>
									<p>
<!-- END LOCATION -->
<!-- START WEB URL -->
<h6> <i class="fa fa-link"> </i> <th><%= model_class.human_attribute_name(:URL) %></th></h6>
<!-- END WEB URL -->
<!-- Post Date (date when idea was posted on launcherr) -->

<h6> <i class="fa fa-clock-o"> </i> <th><%= model_class.human_attribute_name(:created_at) %></th>.</h6><br><br>


									<!-- START QUICK PITCH -->
                                   <th><%= model_class.human_attribute_name(:quick_pitch) %></th>
									</p><br>
 <!-- PULL DATA FROM SKILLS NEEDED -->
						  <div class="entry-content portfolio-content"> <h4><strong> Team Needed</strong></h4></div>

									<ul>
										• Architect
									</ul>
									<ul>
										• Timber Specialist
									</ul>
									<ul>
										• 
									Plumber
									</ul>
								  <ul>
										• Electrician
						  </ul>
									<ul>
										<p>
										•	Handyman									</p>
									</ul>
									<br>
                                    <a href="#" class="sr-button sr-button5 big-button">JØIN TEAM</a></h6>
	
						  <!-- END AVAILABLE POSITIONS -->
                                
                       
								<br>
                                <br><div class="entry-content portfolio-content"> <h4><strong> Project By</strong></h4></div>
                               <!-- Project by  #insert users details-->
						  <div class="project-by"><!-- pull display picture -->
									<img src="files/uploads/G8ncMfNA.jpeg" width="200" height="201">

						  </div> 
								<!-- insert post authors name--><h6> Jake Baird</h6><br>
								<!-- insert post authors 140 character bio--> I'm a full stack developer based in Sydney / NYC.  I'm Passionate about tech, nature and living off the grid. 

						  <!-- START TAGS  -->
								<div class="widget tag-widget">
									<h6 class="widget-title"><strong>Tags</strong></h6>
									<div class="tag-list">
										<p><a href="#" title="design Tag" class="design-2">Log Cabin</a>
										  <a href="#" title="fiji Tag" class="fiji">Eco Friendly</a>
										  <a href="#" title="motion Tag" class="motion-2">Build</a>
										  <a href="#" title="music Tag" class="music-2">Idea</a>
										  <a href="#" title="photography Tag" class="photography-2">Snow</a>
										  <a href="#" title="surf Tag" class="surf">Summer</a>
									  </p>
										<br> <br> <%= link_to post_path(post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
									</div>
								</div></div>
								<!-- End tag-widget -->

								<!-- SIDEBAR -->

						</div>
						<!-- END .wrapper -->

						<div class="spacer spacer-big"></div>

					</div>
					<!-- END #portfolio-single .section-inner --><!-- END SECTION #portfolio-->
					<!-- PORTFOLIO SECTION -->

					
                    

		</div>
		<!-- END .page-body -->

		<!-- MODALS --><!-- /.modal -->

		<!-- PAGEBODY -->

	  </div>
      
      